services:
  prestashop:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    image: patrykswietlik/project-prestashop:latest
    ports:
      - 18977:443
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
    networks:
      - admin-mysql_default

  memcached:
    image: memcached:latest
    ports:
      - '11211:11211'
      
networks:
  admin-mysql_default:
    external: true
