services:
  prestashop:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    image: patrykswietlik/project-prestashop:latest
    ports:
      - 18977:443
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_189774
      DB_USER: root
      DB_PASSWD: student
    networks:
      - admin-mysql_default

  memcached:
    image: memcached:latest
    ports:
      - '11211:11211'
    networks:
      - prestashop_network
      
networks:
  admin-mysql_default:
    external: true
