services:
  prestashop:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    image: patrykswietlik/project-prestashop:latest
    container_name: prestashop
    ports:
      - 18977:443
    depends_on:
      - mysql
    environment:
      DB_SERVER: prestashop-db
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: prestashop
    networks:
      - prestashop_network

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - '11211:11211'
    networks:
      - prestashop_network
      
networks:
  admin-mysql_default:
    external: true
